name: 'Git Secrets Scan'
description: 'Scan repository for secrets using git-secrets'

runs:
  using: "composite"
  steps:
    - name: Install and configure git-secrets
      shell: bash
      run: |
        git clone https://github.com/awslabs/git-secrets.git
        cd git-secrets
        git checkout 1.3.0
        sudo make install
        cd ..
        git secrets --install
        git secrets --register-aws

    - name: Run git-secrets scan
      shell: bash
      run: git secrets --scan-history
